config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :annotations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'translations#archerhind'

end

app/models/annotation.rb
class Annotation < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  before_action :set_annotation, only: [:show, :edit, :update, :destroy]

  # GET /annotations
  # GET /annotations.json
  def index
    @annotations = Annotation.all
  end

  # GET /annotations/1
  # GET /annotations/1.json
  def show
  end

  # GET /annotations/new
  def new
    @annotation = Annotation.new
  end

  # GET /annotations/1/edit
  def edit
  end

  # POST /annotations
  # POST /annotations.json
  def create
    @annotation = Annotation.new(annotation_params)

    respond_to do |format|
      if @annotation.save
        format.html { redirect_to @annotation, notice: 'Annotation was successfully created.' }
        format.json { render :show, status: :created, location: @annotation }
      else
        format.html { render :new }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annotations/1
  # PATCH/PUT /annotations/1.json
  def update
    respond_to do |format|
      if @annotation.update(annotation_params)
        format.html { redirect_to @annotation, notice: 'Annotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @annotation }
      else
        format.html { render :edit }
        format.json { render json: @annotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annotations/1
  # DELETE /annotations/1.json
  def destroy
    @annotation.destroy
    respond_to do |format|
      format.html { redirect_to annotations_url, notice: 'Annotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annotation
      @annotation = Annotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annotation_params
      params.require(:annotation).permit(:title, :text, :source, :source)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if User.count == 1
      if user_signed_in?
        redirect_to root_path
      else
        redirect_to new_user_session_path
      end
    end
  end

end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/annotations/_form.html.erb
<%= form_with(model: annotation, local: true) do |form| %>
  <% if annotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(annotation.errors.count, "error") %> prohibited this annotation from being saved:</h2>

      <ul>
      <% annotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/annotations/edit.html.erb
<h1>Editing Annotation</h1>
<% if user_signed_in? %>
<%= render 'form', annotation: @annotation %>
<%= link_to 'Show', @annotation %> |
<% else %>
<p>You are not authorized to view this page.</p>
<% end %>
<%= link_to 'Back', annotations_path %>

app/views/annotations/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col">
  <h1>Annotations</h1>
    </div>
    <div class="col">
      <div class="input-group">
	<%= form_tag(annotations_path, :method => "get", id: "search-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search Annotations", class: 'form-control' %>
	<span class="input-group-btn">
	  <%= submit_tag "Search", class: 'button' %>
	</span>
	<% end %>
      </div>
      <br/>
    </div>
  </div>
  

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Text</th>
      <th>Source</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @annotations.each do |annotation| %>
      <tr>
        <td><%= annotation.id %></td>
	<td><%= annotation.title %></td>
        <td><%= annotation.text %></td>
        <td><%= annotation.source %></td>
        <td><%= image_tag annotation.source %></td>
        <td><%= link_to 'Show', annotation %></td>
	<% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_annotation_path(annotation) %></td>
        <td><%= link_to 'Destroy', annotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% else %>
	<p></p>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Annotation', new_annotation_path %>
</container>

app/views/annotations/new.html.erb
<h1>New Annotation</h1>
<% if user_signed_in? %>
<%= render 'form', annotation: @annotation %>
<% else %>
<p>You are not authorized to use this page</p>
<% end %>
<%= link_to 'Back', annotations_path %>

app/views/annotations/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @annotation.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @annotation.text %>
</p>

<p>
  <strong>Source:</strong>
  <%= @annotation.source %>
</p>

<p>
  <strong>Source:</strong>
  <%= image_tag @annotation.source %>
</p>

<%= link_to 'Edit', edit_annotation_path(@annotation) %> |
<%= link_to 'Back', annotations_path %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><strong><%= link_to "OpenTimaeus", root_path, {:style => 'color: black'} %></strong></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Updates<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <li class="nav-link"><%= link_to "Annotations", annotations_path %></li>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Translations
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Archer-Hind Translation</a>
          <a class="dropdown-item disabled" href="#">Jowett Translation</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Submit a Translation</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Media</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenTimaeus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render partial: "layouts/header"  %>
    </div>
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% if user_signed_in? %>
      <%= link_to('logout', destroy_user_session_path, method: :delete) %>
      <% end %>

    <div>
  </body>
</html>

app/views/translations/archerhind.html.erb
<div class="container clearfix">
<div class="row">
  <div class="col">
    <%= render partial: "translations/timaeus-ah" %>
</div>
<div class="col-3">
  <div id="sidebar">
    <div class="sidebar__inner">
      <p><center><%= image_tag "plato-thumb.png" %></center></p>
      <p>
	<!-- -->
<ul class="accordion">
	  <li>
	  	<button class="accordion-control">Introduction</button>
	  	<div class="accordion-panel">Socrates Summary<br/>Athens v. Atlantis</div>
	  </li>
	  <li>
	  	<button class="accordion-control">Timaeus' Discourse</button>
	  	<div class="accordion-panel">Being/Becoming<br/>The Universe</div>
	  </li>
	  <li>
	  	<button class="accordion-control">The Intellectual Creation</button>
	  	<div class="accordion-panel">The World as Living Thing<br/>The World Body<br/>The World Soul</div>
	  </li>
	</ul>
	<!-- -->
      </p>
    </div>
  </div>
</div>
  <script type="text/javascript">
    var a = new StickySidebar('#sidebar', {
    topSpacing: 20,
    bottomSpacing: 20,
    containerSelector: '.container',
    innerWrapperSelector: '.sidebar__inner'
    });
  </script>
  <script>
    $(document).ready(function() {

    $('.accordion').on('click', '.accordion-control', function(e) {
    e.preventDefault();
    $(this).next('.accordion-panel').not(':animated').slideToggle();
    });
    });
  </script>
  
</div>
</div>
</div>
</div>

app/views/welcome/index.html.erb
<h2>Hello World</h2>

<p>The time is now: <%= Time.now %></p>